### ISSUE TITLE
An app crushes if tries to import working server

### ISSUE THREAD

**Issue by MaxLevs** [ForkGG/Fork-legacy#25]
_Fork crushes if you try to import server what is working._

**Steps to reproduce**: Start minecraft server manualy (out of Fork), start the Fork and try to import the server
**Actual behavior**: Application crushes without single message
**Expected behavior**: Warning message "Choosen server is working now." without crush and stop iimporting or try to finish importing.

**Comment by mallaaiden** [comment]
> _Fork crushes if you try to import server what is working._
> 
> **Steps to reproduce**: Start minecraft server manualy (out of Fork), start the Fork and try to import the server **Actual behavior**: Application crushes without single message **Expected behavior**: Warning message "Choosen server is working now." without crush and stop iimporting or try to finish importing.

Have you tried reinstalling Fork or making sure you have enough RAM to import?

**Comment by MaxLevs** [comment]
> > _Fork crushes if you try to import server what is working._
> > **Steps to reproduce**: Start minecraft server manualy (out of Fork), start the Fork and try to import the server **Actual behavior**: Application crushes without single message **Expected behavior**: Warning message "Choosen server is working now." without crush and stop iimporting or try to finish importing.
> 
> Have you tried reinstalling Fork or making sure you have enough RAM to import?

I have about 40 GB ram available. And yes I've tried to reinstall Fork. 

But this Issue is outdated. I don't use Fork now but docker.
This issue is all about providing feedback to community to make tools better.

**Comment by ChristianKernDev** [comment]
Probably fixed with #44
