### ISSUE TITLE
Need to error trap "Failed connection to discord-ipc-(X)" otherwise it bloats consoleLog.txt

### ISSUE THREAD

**Issue by The-Monkey-King** [ForkGG/Fork-legacy#30]
Issue: failing a connection to discord fills the consoleLog.txt while Fork is running.

Suggestions: 

1. Application should only attempt to connect to discord-ipx-(0-9) three times. (30 attempts to reach any discord-ipx)
2. Application connection attempts to be recorded in consoleLog.txt as "attempting to connect to discord-ipx.. (1 of 3)" ex cetera.
3. When the application fails to connect to discord-ipx-(0-9) (times out), after three tries, the message should be placed in the error log, "Failed to reach discord IPX."

[consoleLog.txt](https://github.com/ForkGG/Fork/files/7357812/consoleLog.txt)

**Comment by ChristianKernDev** [comment]
This can not be trapped, as it is logged by the DiscordRPC package. This is intended and won't be fixed:
https://github.com/Lachee/discord-rpc-csharp/issues/142

Disabled logging for DiscordRPC errors as a fix
