### ISSUE TITLE
Deleting a plugin creates a NullReferenceException due to hardcoded reference

### ISSUE THREAD

**Issue by The-Monkey-King** [ForkGG/Fork-legacy#31]
Logic and IO exceptions caused by (I think) hard coded references to the application owner. 

"C:\Users\chris\Source\Repos\fork\logic\..." 

See attached error log: 

[errorLog.txt](https://github.com/ForkGG/Fork/files/7357817/errorLog.txt)

**Comment by ChristianKernDev** [comment]
There is no reference in the code. This is just for creating the stacktrace. The error is probablly somewhere else. As the errorLog is not there anymore and there were some fixes regarding this in #44 i will close this issue for now
