### ISSUE TITLE
Server stuck on "Joining World..." for Paper

### ISSUE THREAD

**Issue by mallaaiden** [ForkGG/Fork-legacy#38]
Hi. I created a server on Paper and installed no addons yet. When I attempted to join my server when it said it was on, I was stuck on the `Joining World` screen. How do I fix that or is that a glitch?
(It has 50% CPU Usage, 46% RAM Usage, and 61% DISK Usage)
(I was running Lunar Client at the time, didn't check regular Minecraft Launcher)

**Comment by PenguCCN** [comment]
Check your console to see if anything shows up, however you may just be experiencing a bug with paper. Maybe try dropping in a paper fork to see if your issue is resolved.

**Comment by mallaaiden** [comment]
Yea, I found out how to fix it. Thanks!
