### ISSUE TITLE
What does this do? What does it do better than RDP?

### ISSUE THREAD

**Issue by allanonmage** [ForkGG/Fork-legacy#39]
You seem to be the only product in your category (or maybe just the top as far as search goes, I haven't looked that hard yet), but your FAQ seems to be aimed at nontechnical people, which is at odds for what you offer.

I missed the screenshots the first 3 times I looked due to the dark tone and complete lack of contrast on your site, so maybe I'm also missing something else that's supposed to be obvious.

What does your software do better than an RDP session with the console, notepad++, and task manager?  I don't have Discord because Discord hates me and banned me **_while signing up_** like 10 years ago, so I never saw a point of trying to fix the account.

**Comment by PenguCCN** [comment]
Fork-GG is a easy to use windows client for managing MC Servers. Not everyone knows how to RDP, I used to run a game host and I've learned that while many users know how to run a server, many just don't understand the more in depth technical stuff. So asking people to RDP can simply be too much. I've used Fork for personal reasons in the past and honestly it's really good. The upcoming update is supposed to bring large improvements to overhaul the UI and make it even easier to use while still giving more options.
