### ISSUE TITLE
After Installing ForkLauncher.exe, the software doesn't shown on the windows menu.

### ISSUE THREAD

**Issue by OPADILOP** [ForkGG/Fork-legacy#47]
![image](https://github.com/ForkGG/Fork-legacy/assets/86042583/1faba065-b82a-4df1-b8ca-0293489f0501)

**Comment by OPADILOP** [comment]
No fork launcher software...

**Comment by ChristianKernDev** [comment]
The Fork Launcher is not an installer. Put it somewhere where you find it (like Desktop) and just execute it. You can add it to the startmenu after that
